# Generated by Django 4.2.5 on 2023-10-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_is_active_variation_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='is_available',
            new_name='is_active',
        ),
    ]
